#can be many wiki & many www sites

[server]
port = 3000
addr = "0.0.0.0"


[[wiki]]
#unique name for the wiki
name = "legal"
title = "Legal docs"
#http or git url
url = "https://github.com/threefoldfoundation/legal"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = ""


[[wiki]]
name = "tftech"
title = "TFTech"
url = "github.com/threefoldtech/info_tftech"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = ""
